/**
 * Pure half of the analytics session clock.
 *
 * `MediaAnalyticsEvent.session_id` has been on the wire type — and normalised
 * server-side by `eventService.normaliseEvent` — since Casa Media shipped, but
 * nothing ever populated it. Without it "sessions generated" (§41) and "average
 * session duration" (§43) have no input at all: `media_events` can be grouped by
 * user or by day, but not into visits.
 *
 * A session is a run of activity with no gap longer than `SESSION_IDLE_MS`. That
 * is the whole rule, and it is worth having on its own because the two ways to
 * get it wrong are both invisible in a running app: a session that never rolls
 * over makes every "duration" the age of the install, and one that rolls over on
 * every event makes every session zero seconds long.
 *
 * Free of react-native / expo imports so `node --test` can exercise it — see
 * `utils/__tests__/session.test.mts`. `services/AnalyticsService.ts` is the
 * stateful shell that persists the result and supplies the fresh ids.
 */

export const SESSION_STORAGE_KEY = 'casa_media_session';

/**
 * Thirty minutes, the same idle window the rest of the analytics industry uses.
 * Long enough that reading an article and coming back is one visit; short enough
 * that tomorrow morning is a new one.
 */
export const SESSION_IDLE_MS = 30 * 60 * 1000;

/** A session that never ends is a bug, not a very engaged user. */
export const SESSION_MAX_MS = 4 * 60 * 60 * 1000;

export interface SessionState {
  id: string;
  /** Epoch ms of the first event in this session. */
  startedAt: number;
  /** Epoch ms of the most recent event. */
  lastSeenAt: number;
}

export interface SessionResolution {
  state: SessionState;
  /** True when `freshId` was taken up, i.e. this event opens a new session. */
  started: boolean;
}

/**
 * Decide which session an event occurring at `now` belongs to.
 *
 * `freshId` is generated by the caller on every call — ids are cheap and this
 * keeps the decision pure. It is used only when a new session actually starts.
 *
 * A new session starts when there is no prior state, when the gap since the last
 * event exceeds `idleMs`, when the prior session has run longer than
 * `SESSION_MAX_MS`, or when the clock has moved backwards past the session start
 * (a timezone change or an NTP correction, which would otherwise produce a
 * negative duration).
 */
export function resolveSession(
  prior: SessionState | null,
  now: number,
  freshId: string,
  idleMs: number = SESSION_IDLE_MS,
  maxMs: number = SESSION_MAX_MS,
): SessionResolution {
  const open = (): SessionResolution => ({
    state: { id: freshId, startedAt: now, lastSeenAt: now },
    started: true,
  });

  if (!prior) return open();
  if (now - prior.lastSeenAt > idleMs) return open();
  if (now - prior.startedAt > maxMs) return open();
  if (now < prior.startedAt) return open();

  return {
    // `lastSeenAt` advances, `startedAt` does not — a clock that jitters
    // backwards inside the window must not shorten the session retroactively.
    state: { ...prior, lastSeenAt: Math.max(prior.lastSeenAt, now) },
    started: false,
  };
}

/** Parse persisted state, returning null for anything malformed. */
export function parseSession(raw: string | null): SessionState | null {
  if (!raw) return null;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== 'object') return null;
  const candidate = parsed as Record<string, unknown>;
  if (typeof candidate.id !== 'string' || !candidate.id) return null;
  if (typeof candidate.startedAt !== 'number' || !Number.isFinite(candidate.startedAt)) {
    return null;
  }
  if (typeof candidate.lastSeenAt !== 'number' || !Number.isFinite(candidate.lastSeenAt)) {
    return null;
  }
  return {
    id: candidate.id,
    startedAt: candidate.startedAt,
    lastSeenAt: candidate.lastSeenAt,
  };
}
